version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - celery

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    command: sh -c "sleep 10 && celery -A celery_tasks worker --loglevel=info"
    depends_on:
      - rabbitmq
      - redis

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
